{% set name = "recordclass" %}
{% set version = "0.24" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/recordclass-{{ version }}.tar.gz
  sha256: dc6e46aec90d5b185576fce40ffc875488b04692a9259265c965fac150630d06

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  imports:
    - recordclass
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/intellimath/recordclass
  summary: Mutable variant of namedtuple -- recordclass, which support assignments, compact dataclasses and other memory saving variants.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - druvus
