{% set name = "recordclass" %}
{% set version = "0.22.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/recordclass-{{ version }}.tar.gz
  sha256: c2c49556d88d45b090d4440c4672a6dffc912c10386fef9b100d2f657ee3ee64

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - recordclass
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/intellimath/recordclass
  summary: Mutable variant of namedtuple -- recordclass, which support assignments, compact dataclasses and other memory saving variants.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - druvus
